export const states = [
  { initials: 'AC', fullName: 'Acre' },
  { initials: 'AL', fullName: 'Alagoas' },
  { initials: 'AM', fullName: 'Amazonas' },
  { initials: 'AP', fullName: 'Amapa' },
  { initials: 'BA', fullName: 'Bahia' },
  { initials: 'CE', fullName: 'Ceara' },
  { initials: 'DF', fullName: 'Distrito Federal' },
  { initials: 'ES', fullName: 'Espirito Santo' },
  { initials: 'GO', fullName: 'Goias' },
  { initials: 'MA', fullName: 'Maranhao' },
  { initials: 'MG', fullName: 'Minas Gerais' },
  { initials: 'MS', fullName: 'Mato Grosso do Sul' },
  { initials: 'MT', fullName: 'Mato Grosso' },
  { initials: 'PA', fullName: 'Para' },
  { initials: 'PB', fullName: 'Paraiba' },
  { initials: 'PE', fullName: 'Pernambuco' },
  { initials: 'PI', fullName: 'Piaui' },
  { initials: 'PR', fullName: 'Parana' },
  { initials: 'RJ', fullName: 'Rio de Janeiro' },
  { initials: 'RN', fullName: 'Rio Grande do Norte' },
  { initials: 'RO', fullName: 'Rondonia' },
  { initials: 'RR', fullName: 'Roraima' },
  { initials: 'RS', fullName: 'Rio Grande do Sul' },
  { initials: 'SC', fullName: 'Santa Catarina' },
  { initials: 'SE', fullName: 'Sergipe' },
  { initials: 'SP', fullName: 'Sao Paulo' },
  { initials: 'TO', fullName: 'Tocantins' },
];
